version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.30
    volumes:
      - 'datadb:/var/lib/mysql'
      - './docker/mysql/create-db-testing.sh:/docker-entrypoint-initdb.d/10-create-db-testing.sh'
    ports:
      - "33060:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "${MYSQL_ROOT_HOST}"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: '${MYSQL_ALLOW_EMPTY_PASSWORD}'
    healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    
volumes:
  datadb:
    driver: local